import { expect,it } from 'vitest';
import { applyAction,getLegalActions,getPlayerView } from '../../src/mahjong/game';
import { fixture,chiFixture,robKongFixture,selfDrawFixture,allTiles } from './fixtures';
import type { GameState,Seat,ActionKind } from '../../src/mahjong/game-types';
function invariant(s:GameState){const ts=allTiles(s);expect(ts).toHaveLength(s.mode==='flowers'?144:136);expect(new Set(ts.map(t=>t.id)).size).toBe(ts.length);}
function act(s:GameState,seat:Seat,kind:ActionKind,code?:string){const a=getLegalActions(s,seat).find(a=>a.kind===kind&&(!code||a.tileIds.some(id=>s.players.find(p=>p.seat===seat)!.hand.find(t=>t.id===id)?.code===code)));expect(a).toBeDefined();const out=applyAction(s,a!);expect(out.ok).toBe(true);invariant(out.state);return out.state;}
function passes(s:GameState){while(s.pendingWindow){const seat=s.pendingWindow.eligibleSeats.find(seat=>!s.pendingWindow!.responses[seat])!;s=act(s,seat,'pass');}return s;}
it('R3 three chi choices only for next player; claim does not draw',()=>{let s=act(chiFixture(),'east','discard','C3');expect(getLegalActions(s,'south').filter(a=>a.kind==='chi')).toHaveLength(3);expect(getLegalActions(s,'west').some(a=>a.kind==='chi')).toBe(false);const n=s.wall.length;s=act(s,'south','chi');s=passes(s);expect(s.activeSeat).toBe('south');expect(s.wall.length).toBe(n);expect(s.players[1].hand).toHaveLength(14);});
it('R4 pong beats chi independently of reply order',()=>{for(const order of [['south','west'],['west','south']] as Seat[][]){let s=act(fixture({east:'C3',south:'C1 C2 C4 C5',west:'C3 C3'}),'east','discard','C3');const n=s.wall.length;for(const seat of order)s=act(s,seat,seat==='south'?'chi':'pong');s=passes(s);expect(s.activeSeat).toBe('west');expect(s.wall.length).toBe(n);}});
it('R5 nearest winner wins even when north replies first',()=>{let s=act(fixture({east:'DR',west:'C1 C2 C3 C4 C5 C6 D1 D2 D3 B1 B2 B3 WE WE WE DR',north:'C1 C2 C3 C4 C5 C6 D1 D2 D3 B1 B2 B3 WS WS WS DR'}),'east','discard','DR');s=act(s,'north','win');expect(s.phase).toBe('await-responses');s=act(s,'west','win');s=passes(s);expect(s.result).toMatchObject({kind:'win',winner:'west',method:'discard',sourceSeat:'east'});expect(getLegalActions(s,'east')).toEqual([]);});
it('R6 concealed kong hides face and draws tail without robbery',()=>{let s=fixture({east:'C3 C3 C3 C3'});const last=s.wall.at(-1)!;s=act(s,'east','concealed-kong');expect(s.pendingWindow).toBeNull();expect(s.players[0].hand.some(t=>t.id===last.id)).toBe(true);expect(s.players[0].melds[0].tiles).toHaveLength(4);expect(getPlayerView(s,'south').players[0].melds[0].tiles).toEqual([]);});
it('R6 exposed kong draws tail',()=>{let s=act(fixture({east:'C3',south:'C3 C3 C3'}),'east','discard','C3');const last=s.wall.at(-1)!;s=act(s,'south','exposed-kong');s=passes(s);expect(s.players[1].melds[0].kind).toBe('exposed-kong');expect(s.players[1].hand.some(t=>t.id===last.id)).toBe(true);});
it('R7 robbery keeps original pong and moves winning tile',()=>{let s=robKongFixture();const n=s.wall.length;s=act(s,'east','added-kong');expect(s.phase).toBe('await-kong-responses');s=act(s,'south','win');s=passes(s);expect(s.result).toMatchObject({kind:'win',method:'rob-kong',winner:'south'});expect(s.players[0].melds[0].kind).toBe('pong');expect(s.wall.length).toBe(n);});
it('R7 passed robbery completes added kong',()=>{let s=robKongFixture();const n=s.wall.length;s=passes(act(s,'east','added-kong'));expect(s.players[0].melds[0].kind).toBe('added-kong');expect(s.wall.length).toBe(n-1);});
it('W4 self draw references hand and blocks further moves',()=>{const s=act(selfDrawFixture(),'east','win');expect(s.result).toMatchObject({method:'self-draw',winner:'east'});expect(getLegalActions(s,'east')).toEqual([]);});
it('R8 repeated flowers at head then tail',()=>{let s=fixture({east:'C3'},[],'flowers');const pull=(code:string)=>s.wall.splice(s.wall.findIndex(t=>t.code===code),1)[0];const a=pull('F1'),b=pull('F2'),c=pull('D5');expect(a&&b&&c).toBeTruthy();s.wall.unshift(a);s.wall.push(c,b);s=passes(act(s,'east','discard','C3'));expect(s.players[1].flowers.map(t=>t.code)).toEqual(['F1','F2']);expect(s.players[1].hand.some(t=>t.id===c.id)).toBe(true);});
it('R9 R10 W5 reserve and flower replacement boundaries preserve tiles',()=>{for(const flower of [false,true]){let s=fixture({east:'C3'},[],flower?'flowers':'no-flowers');const top=flower?s.wall.splice(s.wall.findIndex(t=>t.code==='F1'),1)[0]:s.wall.shift()!;while(s.wall.length>16)s.players[3].discards.push(s.wall.pop()!);s.wall.unshift(top);s=passes(act(s,'east','discard','C3'));expect(s.wall).toHaveLength(16);if(flower)expect(s.result).toEqual({kind:'draw',reason:'reserve-exhausted'});else{expect(s.phase).toBe('await-discard');s=passes(act(s,'south','discard'));expect(s.result).toEqual({kind:'draw',reason:'reserve-exhausted'});}invariant(s);}});
it('R11 stale window, duplicate response and wrong player remain unchanged',()=>{let s=act(robKongFixture(),'east','added-kong');const a=getLegalActions(s,'south')[0];expect(applyAction(s,{...a,windowId:'old'})).toMatchObject({ok:false,state:s});expect(applyAction(s,{...a,seat:'east'})).toMatchObject({ok:false,state:s});s=applyAction(s,a).state;expect(applyAction(s,a)).toMatchObject({ok:false,state:s});});
it('R4 win beats both pong and earlier chi',()=>{let s=act(fixture({east:'C3',south:'C1 C2 C4 C5',west:'C3 C3',north:'C1 C2 C4 C5 C6 D7 D8 D9 B1 B1 B1 WE WE WE DR DR'}),'east','discard','C3');s=act(s,'south','chi');expect(s.phase).toBe('await-responses');s=act(s,'west','pong');expect(s.phase).toBe('await-responses');s=act(s,'north','win');expect(s.result).toMatchObject({winner:'north',method:'discard'});});
it('claim origin prevents a second draw-only kong or self-draw',()=>{let s=act(chiFixture(),'east','discard','C3');s=passes(act(s,'south','chi'));expect(getLegalActions(s,'south').every(a=>a.kind==='discard')).toBe(true);});
